version: '4'
services:
  mongodb:
    image: mongo:8.0
    container_name: mongo-demo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: Qwerty123
      MONGO_INITDB_ROOT_DATABASE: product-service
    volumes:
      - ./data:/data/db
