version: '4'
services:
  mysql:
    image: mysql:9.0.1
    container_name: inventory-service-mysql
    ports:
      - "3316:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    volumes:
        - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
        - ./docker/mysql/data:/var/lib/mysql